### ISSUE TITLE
{tabulizer} got archived on CRAN on 2021-10-31

### ISSUE THREAD

**Issue by pat-s** [ropensci/tabulapdf#140]
Are there short-term plans to bring it back? :)

**Comment by maelle** [comment]
:wave: @tpaskhalis, do you need any help?

**Comment by tpaskhalis** [comment]
The release of Java 17 caused some issues in the way R interacts with it through rJava. More specifically from Brian Ripley's email:

```
On the most common form of failure (all but jsr223, also seen in rJava),
Simon Urbanek writes

"There was a major change in JDK-17 that now disallows reflection to use
non-public access.  In short rJava can no longer pretend it is part of a
class when accessing methods/fields which allowed us to call methods
without explicitly subclassing a class.  This may have serious
repercussions, because code that could be before written in R now has to
be written in Java, compiled and then called from R."
```

It's not the best of timing for me, as it all occurred at the beginning of a new teaching semester. And also my Java is not that strong, so it will take me some time to figure this issue. But it's definitely fixable. If anybody wants to take a shot at pull request, I'd be more than happy.

@maelle, thanks, yes, I'd be happy with any help on this issue. But it's certainly on my to-do list, if nobody else attends to it. Seems like it still works with GH installation for some people.

**Comment by maelle** [comment]
@tpaskhalis Thanks for your answer! As it's not something I would personally be able to help with, I've added the "help wanted" label (we're working on making such issues more easily discoverable cc @steffilazerte), and have posted in rOpenSci slack package-maintenance channel.

**Comment by DavidPerea** [comment]
So right now there is no way to use it, right?

As I am a novice user, I don't know a lot about programming to help, but a lot of encouragement!

**Comment by pat-s** [comment]
@DavidPerea You can install it from GitHub, which should work: `remotes::install_github("ropensci/tabulizer")`.

**Comment by DavidPerea** [comment]
> @DavidPerea You can install it from GitHub, which should work: `remotes::install_github("ropensci/tabulizer")`.

Before installing "tabulizer", I see that I must first have 'tabulizerjars' installed. But I get the following error when using this command: `remotes :: install_github ("ropensci / tabulizerjars")`

```
Downloading GitHub repo ropensci/tabulizerjars@HEAD
Running `R CMD build`...
* checking for file 'C:\Users\david\AppData\Local\Temp\Rtmp8ee6dr\remotesf0472d62281\ropensci-tabulizerjars-d1924e0/DESCRIPTION' ... OK
* preparing 'tabulizerjars':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'tabulizerjars_1.0.1.tar.gz'
* installing *source* package 'tabulizerjars' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'tabulizerjars'
    finding HTML links ... done
    tabulizerjars                           html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
Error: package or namespace load failed for 'tabulizerjars':
 .onLoad failed in loadNamespace() for 'tabulizerjars', details:
  call: NULL
  error: .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JAVA_HOME cannot be determined from the Registry
Error: loading failed
Ejecución interrumpida
ERROR: loading failed for 'x64'
* removing 'C:/Users/david/OneDrive/Documentos/R/win-library/R-4.1.2/library/tabulizerjars'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/david/AppData/Local/Temp/Rtmp8ee6dr/filef042d3e148b/tabulizerjars_1.0.1.tar.gz’ had non-zero exit status
```

How is it solved?

**Comment by tpaskhalis** [comment]
@DavidPerea make sure that you can install and load `rJava` before installing `tabulizerjars`.

**Comment by DavidPerea** [comment]
> @DavidPerea make sure that you can install and load `rJava` before installing `tabulizerjars`.

Solved, thank you very much!

**Comment by budall** [comment]
Hi, I'm in same boat. Would like to use this package, but the remotes :: install_github ("ropensci / tabulizerjars") fails like this:

remotes::install_github("ropensci/tabulizer")
Downloading GitHub repo ropensci/tabulizer@HEAD
Skipping 1 packages not available: tabulizerjars
✓  checking for file ‘/private/var/folders/55/2g40bwx56rvg3bnchwhvqkdr0000gn/T/Rtmp3jLMsJ/remotes6afbece498f/ropensci-tabulizer-9f45f91/DESCRIPTION’ ...
─  preparing ‘tabulizer’:
✓  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘tabulizer/docs’
─  building ‘tabulizer_0.2.2.tar.gz’
   
ERROR: dependency ‘tabulizerjars’ is not available for package ‘tabulizer’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/tabulizer’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/55/2g40bwx56rvg3bnchwhvqkdr0000gn/T//Rtmp3jLMsJ/file6afb93f52e1/tabulizer_0.2.2.tar.gz’ had non-zero exit status
> 

rJava is installed and loaded - and I don't get any obvious errors from it.

This is a Mac. Happy to move to a PC/Ubuntu if that is an easier path. 



Any clues? Really, really could use this package right now!

thanks,

**Comment by budall** [comment]
I got this working.  It was simple.

You need this:

remotes::install_github(c("ropensci/tabulizerjars", "ropensci/tabulizer")

**Comment by ddkapan** [comment]
For macOS >= to Catalina, it won’t work b/c the relevant legacy Java runtime (SE 6) is not compatible, downgrade OS, switch OS systems or find an alternative application.

**Comment by araceliramirezg** [comment]
Hi!

> @DavidPerea You can install it from GitHub, which should work: `remotes::install_github("ropensci/tabulizer")`.

I tried this but I had this error

`Downloading GitHub repo ropensci/tabulizer@HEAD
Error: Failed to install 'tabulizer' from GitHub:
  invalid octal digit`

Help, please! i need tu use this package

**Comment by pat-s** [comment]
@araceliramirezg This seems to be a separate issue of your local R installation. I suggest to open a new issue and provide more information on your local R installation. You might use the [reprex](https://github.com/tidyverse/reprex) package to provide this information.

**Comment by araceliramirezg** [comment]
> @araceliramirezg This seems to be a separate issue of your local R installation. I suggest to open a new issue and provide more information on your local R installation. You might use the [reprex](https://github.com/tidyverse/reprex) package to provide this information.

@pat-s I tried it again and i have this message:

`remotes::install_github("ropensci/tabulizer")
Downloading GitHub repo ropensci/tabulizer@HEAD
Downloading GitHub repo ropensci/tabulizerjars@HEAD
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\pc\AppData\Local\Temp\RtmpY7EkSu\remotes9e414fe2c0a\ropensci-tabulizerjars-d1924e0/DESCRIPTION' (773ms)
-  preparing 'tabulizerjars':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'tabulizerjars_1.0.1.tar.gz'
   
Installing package into ‘C:/Users/pc/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'tabulizerjars' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'tabulizerjars'
    finding HTML links ... done
    tabulizerjars                           html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
Error: package or namespace load failed for 'tabulizerjars':
 .onLoad failed in loadNamespace() for 'tabulizerjars', details:
  call: NULL
  error: .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error: loading failed
Ejecución interrumpida
ERROR: loading failed for 'x64'
* removing 'C:/Users/pc/Documents/R/win-library/4.0/tabulizerjars'
Downloading GitHub repo ropensci/tabulizerjars@HEAD
Skipping tabulizerjars, it is already being installed
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\pc\AppData\Local\Temp\RtmpY7EkSu\remotes9e46a0f279d\ropensci-tabulizer-3049a79/DESCRIPTION' (822ms)
-  preparing 'tabulizer': (391ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'tabulizer/docs'
-  building 'tabulizer_0.2.2.tar.gz'
   
Installing package into ‘C:/Users/pc/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
ERROR: dependency 'tabulizerjars' is not available for package 'tabulizer'
* removing 'C:/Users/pc/Documents/R/win-library/4.0/tabulizer'
Warning messages:
1: In i.p(...) :
  installation of package ‘C:/Users/pc/AppData/Local/Temp/RtmpY7EkSu/file9e42a277c7b/tabulizerjars_1.0.1.tar.gz’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘C:/Users/pc/AppData/Local/Temp/RtmpY7EkSu/file9e4616d358b/tabulizer_0.2.2.tar.gz’ had non-zero exit status`

Help:(

**Comment by jbryer** [comment]
Any update on accepting @AQLT pull request?

**Comment by pat-s** [comment]
Maybe @leeper has time to help here and eventually merge #146?

Otherwise summoning the swiss-knife @jeroen as he did the last commit in the history.

**Comment by maelle** [comment]
#148 :smile_cat:

**Comment by pachadotdev** [comment]
re-added https://cran.r-project.org/package=tabulapdf
