### ISSUE TITLE
q question about package( Tabulizer) installation

### ISSUE THREAD

**Issue by kumarangithub6485** [ropensci/tabulapdf#143]
I am getting below error while I use Tabulizer in R shiny

Error:
`> install.packages("tabulizer")
Warning in install.packages :
package ‘tabulizer’ is not available for this version of R`

How to fix this issue?

**Comment by RobertSellers** [comment]
Do you have JRE installed?  https://www.java.com/en/download/

**Comment by kumarangithub6485** [comment]
@RobertSellers, Yes I had already installed JRE

**Comment by edonnachie** [comment]
Looks like tabulizer had been removed from CRAN:
https://cran.r-project.org/web/packages/tabulizer/index.html

Has this package been abandoned?

**Comment by pachadotdev** [comment]
it has been rebuild as tabulapdf (https://cran.r-project.org/package=tabulapdf)
the README details the installation instructions
