### ISSUE TITLE
Renaming to tabula

### ISSUE THREAD

**Issue by pachadotdev** [ropensci/tabulapdf#153]
I would love to hear some opinions. The package was archived on CRAN.

Comment below, please. Thumbs up = yes, thumbs down = no.

**Comment by billdenney** [comment]
I'd prefer no change.  If the API will remain the same, then I'd prefer for my older code to work without modification.  If the API will change, then changing the name makes sense to me.

**Comment by pachadotdev** [comment]
https://cran.r-project.org/package=tabulapdf
