### ISSUE TITLE
pkgdown building issue

### ISSUE THREAD

**Issue by maelle** [ropensci/tabulapdf#158]
On https://github.com/r-universe/ropensci/actions/runs/3853101829 we see https://github.com/r-universe/ropensci/actions/runs/3853101829/jobs/6565794363

If the vignette needs an external dependency, maybe you could pre-compute it as shown in this post of @jeroen's? https://ropensci.org/blog/2019/12/08/precompute-vignettes/

**Comment by maelle** [comment]
Any update? :smile_cat:

**Comment by pachadotdev** [comment]
> Any update? smile_cat

hi! not yet, unfortunately
I shall add that. In january I checked with the original tabulizer author to fix another issue which is the need to downgrade Java version.

**Comment by maelle** [comment]
:wave: @pachadotdev, I see the build is still failing on https://ropensci.r-universe.dev/builds :slightly_smiling_face:

**Comment by pachadotdev** [comment]
@maelle hi, we need a better fix than a Java downgrade then
let me check this next week

**Comment by maelle** [comment]
wave @pachadotdev, I see the build is still failing on [ropensci.r-universe.dev/builds](https://ropensci.r-universe.dev/builds) slightly_smiling_face

**Comment by pachadotdev** [comment]
hi @maelle !
I have bad news: right now it is extremely hard to use a Java that is not super outdated and against security recommendations. I shall be in touch with the original creator to see how we fix this.

**Comment by maelle** [comment]
:wave: @pachadotdev, any update?

**Comment by pachadotdev** [comment]
yes! I found the problem and needs a lot of refactoring

one step at a time

**Comment by maelle** [comment]
:wave: @pachadotdev, any update?

**Comment by pachadotdev** [comment]
> 👋 @pachadotdev, any update?

the build works now
