### ISSUE TITLE
Is jdk7 -y needed?

### ISSUE THREAD

**Issue by HomeStayMom** [ropensci/tabulapdf#159]
Hi, I wonder if there is specific need to utilize jdk 7 considering I have Java 19 STS from Azul installed.
https://www.azul.com/downloads-new/?os=windows&package=jdk#zulu 

I would be happy to learn if this could work else the proposed method as 
choco install jdk -y results in the following error.
Looking forward hearing from you

C:\Windows\System32>choco install jdk7 -y
Chocolatey v1.3.0
Installing the following packages:
jdk7
By installing, you accept licenses for the packages.
jdk7 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - jdk7 - jdk7 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

C:\Windows\System32>

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

 - ensure that you can install and successfully load [**rJava**](https://cran.r-project.org/package=rJava)
 - [a fully reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) using a publicly available dataset (or provide your data)
 - if an error is occurring, include the output of `traceback()` run immediately after the error occurs
 - the output of `sessionInfo()`

Put your code here:

```R
## rJava loads successfully
# install.packages("rJava")
library("rJava")

## load package
library("tabulizer")

## code goes here


## session info for your system
sessionInfo()
```

**Comment by pachadotdev** [comment]
> 

JDK 7 is required because posterior changes break some methods
we need to fix this during 2023

**Comment by HomeStayMom** [comment]
Hi, I would be happy to see the improvement. Considering the jdk 7!is way out of  lifecycle where install jdk results in error as well jdk 8 is old, would be nice some improvement where more recent and free jdk could be used. Looking forward to it. Good luck and hope to hear from the repo soon!

**Comment by pachadotdev** [comment]
Hola @jazzido 

Sigo con la idea de actualizar tabula. ¿Te parece si nos reunimos durante Marzo para corregir issues como este?

**Comment by HomeStayMom** [comment]
Guys, as a Stay home bored mom who enjoys playing around with tabulaR and trying making to work, I feel would be a great idea.!!!
An other topic might be interesting:
As per Tabula 
" Caveat: Tabula only works on text-based PDFs, not scanned documents. If you can click-and-drag to select text in your table in a PDF viewer (even if the output is disorganized trash), then your PDF is text-based and Tabula should work."

**Comment by pachadotdev** [comment]
@HomeStayMom , I made changes to make it work with OpenJDK 11
