### ISSUE TITLE
Broken link to package documentation, and missing vignette

### ISSUE THREAD

**Issue by dlebauer** [ropensci/tabulapdf#163]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/ropensci/freedomhouse/blob/main/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/freedomhouse/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

- Broken link to package documentation https://docs.ropensci.org/tabulizer
  - I gather it should be changed to https://docs.ropensci.org/tabulapdf
- README references [the vignette vignettes/tabulapdf.Rmd](https://github.com/ropensci/tabulapdf/blob/main/vignettes/tabulapdf.Rmd) that does not appear at https://docs.ropensci.org/tabulapdf

## Reproducible example

- I click the link to documentation available on the github repository page: https://docs.ropensci.org/tabulizer 
- Link opens 404 page

## Expected result

Open documentation page so that I can read vignette

## Session info

NA

**Comment by pachadotdev** [comment]
@ropensci-review-bot build docs

**Comment by cswingle** [comment]
FWIW, I think the doc link just needs to be changed to https://docs.ropensci.org/tabulapdf/

**Comment by pachadotdev** [comment]
> FWIW, I think the doc link just needs to be changed to https://docs.ropensci.org/tabulapdf/

well... you are right

thanks a lot
